keys:
  - &nicole age1qpzyztgsn8cjwg4nhghjtt76g3fn9cjpaf6ghzeg9u02323dhyrsyffw8g
  - &nixie age1ekcstfxpn8zm3up3dgqhgu25jm3tm6h6w5aez7dpyy8r4q9nadxsnasq9z

creation_rules:
  - path_regex: secrets/.*\.(yaml|yml|json|env|ini)$
    key_groups:
      - age:
          - *nicole
          - *nixie